name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: dependency
      run: sudo apt-get -y install valgrind

    - name: Make
      run: make

    - name: Valgrind
      run: make leak-check
